# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "013dmCfNmPJSzOXoODIpegkj1/AN3RLt0UhNgRQ3Z6Dm18agtA2bCAdZg/OIDA+DMKjVGYlyWBSf4NntvPTfys/bd1R18OV8LknO2eMP4yjCPMe2cwtc4xvB+H63RHXE8DwGVgF4R1nRy77lB46IA8uhZXOxbrrRL6UHxZBKw3CjL/9c6LTIs6poBeVh5J+gvRXi+FYz0f672ueTnoYls6TUR+Pl17+1gZkc6eLL5IianyKsf+e+yhfji1iFAiw3XlQ3l2eW4aVyg3XI1A3DMKCPx0ye6JMpdQhb48E64tnI+P7zj414A07YtwMbd78QQ0pZaSjrW0GlMeEsEeclhvRyowhCLBaYO/srGD4cil+7Lq1SvVKt0cw2khpseo3+FO2YS+8pdvsIZbJvMXZjG3xyxLzXKhLyAZ5En0cStSpjBNUhXe4GclhEEf9S2DVS3EIHDk1Rguvz0G74nG5UgAxOQ16mLtr13SZu0JvgFoVtFG6D3ITUnaDLouUUDtVMXPDb9aMM+kcHqFqi3TozLKpYvD10g8YVegOLuSbJvnutIZ0Cl9KfajEPqiTFSZBiYNDyi7gP95GyYfRwBbBXaaEUcPeiK9xYcc4aKaVXDIRrg+Q+wtLaH4KcrwiSw2URtshw7vELbQ2Jx6TmnvEYR76PcevfEIr+o6Xv6ekQdt0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
