travis:
  secure:
    BINSTAR_TOKEN: uyqXKx2sypbAhumwq2FU8lkT7zZcz7hf7Oa3vGrxIwCcxuUyy1/ySmwBMvhnrS9BIKMn8C3M87FB5BWhFiOQl70NdjN6sdlLpS7Xb/IHabZNFI+wEWzLTSaTV4xrVFQzONuCNjBZVltdhlJ6GJK6xoCKHKEdZxyjzYFOMhdfHXSpiKdsg3WlUMyFY+MkJplL+FK7GpPNYDHCpXwNJZIVBmvFhEP1AV55sBsUF0Q0gzu0j1hS1Z1HZxpBWNlP3RNlxxX8BAohV19g1rfSMMvZ8388NbiiLvoP5hOYO8RRicl7CDdp5UfjG6/AeHVDg1BRNuPYjgOXsPHQTOYq37zbUVF0toQIzZ6DrCMpkVyEPSQP6fOm7BJygkuwAFNB84JxwwJYwNFvvL799BsFhF20/M2a98xRGXOoNpEw2Nfh0AZjsGfKqYD7RMlTwScoc2A4Le4PVKt7VM4xtgT9hjYqNrvgVAVyoc4owcXxhAdXjUGd+gdQZF/hpmVGU+RPifZszWVosvDokvJMjGxJhZAiv/n7mrWJctiiPFG43/BB5YaOlkwZjx9Z3uPWMAF9zgfS0Ix4HHbWLH1tw0RSnjvrAaKTY2qNtDmCYtoEB7WqzpdRT3GZwIuvWmGbR0a72JQzfs0nq3nInRl0x9eXNG1oAOTO9v/OPgII3NYjCr3FXz0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
